### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by rYdQ3J9** [robert-alfaro/genius-lyrics#11] opened 2021-05-13 18:04 UTC
ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'genius_lyrics'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'genius_lyrics'

**Comment by gonzotek** [comment] 2021-06-02 18:46
Duplicate of [issue 10](https://github.com/robert-alfaro/genius-lyrics/issues/10). [Pull request](https://github.com/robert-alfaro/genius-lyrics/pull/12) with version key in manifest.json created.

**Comment by robert-alfaro** [comment] 2021-06-10 15:10
Fixed by #12

**Closed** 2021-06-10 15:10 UTC
