### ISSUE TITLE
Improvement: Increase success rate by ignoring songtitle part after a hyphen

### ISSUE THREAD

**Issue by coolinx** [robert-alfaro/genius-lyrics#14] opened 2021-11-15 11:20 UTC
First of all I want to express my gratitude for the creator of this very nice piece of software. I have used it now for a year or so and love it.

I do get a fair number of false hits, where quite common songs are not found in the genius database. Instead it finds some non song text pieces of text which appear book chapters or lists. I noticed this is almost always the case when the song title had a hyphen "-" followed by some text like "live at..." or "featuring...", "Remastered", etc. When searching manually on the Genius webpage, I get the same results.

I think if the software uses only the first part of the song title until the hyphen, and would ignore the rest, the success rate of finding a proper song text would increase a lot.

**Comment by robert-alfaro** [comment] 2021-11-18 04:22
There is/was a deeper root cause to the failure rate.  I too often get what seems like books or plays, e.g. Shakespeare's Hamlet.

At some point I intend on upgrading the underlying genius python library which _I think_ fixes or vastly improves this behavior.  Sorry I have not gotten to it in, well, a long time.  "Soon" I _need_ to upgrade my HA from v0.106.6 to the much evolved latest. I make no promises to get to it really soon, but I will get to it before the end of this year :)

**Comment by coolinx** [comment] 2021-11-18 16:10
I have a nice example to test:
The Rolling Stones Sympathy For The Devil - 50th Anniversary Edition
Instead of song text this gives me some Karl Marx text. similar to if I query genius.com:
https://genius.com/search?q=The Rolling Stones Sympathy For The Devil - 50th Anniversary Edition
But without the part after the hyphen
https://genius.com/search?q=The Rolling Stones Sympathy For The Devil
I get the correct song returned. 
I have this with nearly all song with a hyphen in the song title. Most of the time the part after the hyphen is in fact not part of the song title at all and can be truncated.
Would there be a workaround possible where the part after the hyphen gets ignored in the genuis.com query?

**Comment by robert-alfaro** [comment] 2022-02-25 04:21
I've not forgotten about this...I have done some testing and I do not believe simply removing a hyphen is the solution. There are still varying results and I think I need to dive deeper into the lyricsgenius package to investigate.

**Comment by coolinx** [comment] 2022-02-25 18:49
Awesome that you're looking into this. Very much appreciated!

**Comment by markaggar** [comment] 2023-01-16 19:57
> I've not forgotten about this...I have done some testing and I do not believe simply removing a hyphen is the solution. There are still varying results and I think I need to dive deeper into the lyricsgenius package to investigate.

Were you able to make any progress on this.  Still getting rather peculiar results for songs with hyphens (which on my current playing playlist is most of them!)

**Comment by appsfinder2** [comment] 2023-11-23 22:20
![Overview_–_Home_Assistant](https://github.com/robert-alfaro/genius-lyrics/assets/31155587/d09502a0-45e7-4d62-83c0-aecd15f1e010)
hi got a strange box at the top how can I remove it?

**Comment by robert-alfaro** [comment] 2024-01-12 04:19
I think this is the toughest bug of them all, and it's going to need to be addressed in the library used by this integration. In that library too I recently discovered a bug I intend to "improve" by adding an artist name comparison when a song hit is returned -- I found that some songs would get non-english translation returned because of assumptions and ordering in the http response data handling.

In regards to improving hits, this is one improvement. I need to test and see if those odd scenarios where long play scripts (like Hamlet) are returned go away with this change, as well as possibly increasing the chance for correct song, aside from translation.

**Comment by robert-alfaro** [comment] 2024-01-12 04:20
@appsfinder2 yes, fixed in new refactored branch and applies to #18

**Comment by robert-alfaro** [comment] 2024-01-17 02:11
ultimately created a wrapper class to deal with handling results from song search. The library we depend on is not really getting updated as desired...so...at least we have a way forward.

**Comment by robert-alfaro** [comment] 2024-09-13 23:25
added support for song title to cleverly clean using regex... enjoy!

**Closed by robert-alfaro** 2024-09-13 23:25 UTC
